name: Build & Push to ECR

on:
  push:
    branches: [main]
  workflow_dispatch: {}

env:
  ECR_REPOSITORY: "ack-glue-controller"

jobs:
  build-push:
    name: Build & Push
    runs-on: ubuntu-latest
    environment: production
    # Skip No Deploy commits
    if: "! startsWith(github.event.head_commit.message, 'ND')"
    steps:
      - uses: pathccm/shared-github-actions/build-push@main
        id: build-push
        with:
          docker-repository: ${{ env.ECR_REPOSITORY }}
          push: true
          platforms: linux/arm64
          sbom: true
          provenance: true
          aws-access-key: ${{ secrets.APP_PROD_AWS_ACCESS_KEY_ID }}
          aws-access-secret: ${{ secrets.APP_PROD_AWS_SECRET_ACCESS_KEY }}
          build-args: |
            IMAGE_TAG=latest
